language: node_js
node_js:
- '8'
install:
script: 
addons:
  ssh_known_hosts:
  - 39.108.158.235
before_install:
- openssl aes-256-cbc -K $encrypted_65f08e44a736_key -iv $encrypted_65f08e44a736_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@39.108.158.235 -o StrictHostKeyChecking=no "cnpm i && node /home/travis/web/zhangqiantech-server/app"
